Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 30

Style/SignalException:
  EnforcedStyle: only_raise

Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
