language: ruby
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
rvm:
  - jruby-19mode
  - jruby-head
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.1.6
  - 2.2.2
  - ruby-head
script:
  - rubocop
  - bundle exec rake test
sudo: false
