language: ruby
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
rvm:
  - jruby-head
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - ruby-head
script:
  - rubocop
  - bundle exec rake test
sudo: false
